# ==========================================
# Configuración del Proyecto SonarQube
# ==========================================
sonar.projectKey=riwi-cine-nest
sonar.projectName=Riwi Cine NestJS API
sonar.projectVersion=1.0.0

# Rutas de código fuente y análisis
sonar.sources=src
sonar.tests=test
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts,test/**/*.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**

# Reporte de Cobertura generado por Vitest
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json

# Codificación
sonar.sourceEncoding=UTF-8
