# ==========================================
# SonarQube - Riwi Cine NestJS
# ==========================================

# Identificación del proyecto
sonar.projectKey=riwi-cine-nest
sonar.projectName=Riwi Cine NestJS API
sonar.projectVersion=1.0.0

sonar.host.url=http://localhost:9000

# Código fuente
sonar.sources=src

# Tests
sonar.tests=src,test

# Archivos considerados como tests
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts,**/*.e2e-spec.ts

# Exclusiones
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**

# Cobertura generada por Vitest
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# TypeScript
sonar.typescript.tsconfigPath=tsconfig.json

# Codificación
sonar.sourceEncoding=UTF-8