#!/bin/sh

commit_msg=$(cat "$1")

pattern='^\[US-[0-9]+\] (feat|fix|test|refactor|docs|chore): .+'

if ! echo "$commit_msg" | grep -Eq "$pattern"; then
    echo ""
    echo "❌ Mensaje de commit inválido."
    echo ""
    echo "Formato requerido:"
    echo "[US-XXX] tipo: descripción"
    echo ""
    echo "Tipos permitidos:"
    echo "feat | fix | test | refactor | docs | chore"
    echo ""
    echo "Ejemplo:"
    echo "[US-125] fix: corregir validación de contraseña"
    echo ""
    exit 1
fi